# Generated by Django 2.2.4 on 2019-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredAccounts',
            fields=[
                ('id_secured_account', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=400)),
                ('user', models.BigIntegerField()),
                ('username', models.CharField(max_length=400)),
                ('uri', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'secured_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(blank=True, max_length=45, null=True)),
                ('token', models.CharField(blank=True, max_length=36, null=True)),
                ('created_on', models.CharField(max_length=20)),
                ('last_token', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
